# Custom Tokyonight-night colors
[colors]
background = '#1a1b26'
foreground = '#c0caf5'
cursor = '#c0caf5'

tabs = '#292e42'
tabs-foreground = '#545c7e'
tabs-active = '#7aa2f7'
tabs-active-foreground = '#16161e'

black = '#15161e'
green = '#9ece6a'
red = '#f7768e'
blue = '#7aa2f7'
yellow = '#e0af68'
magenta = '#bb9af7'
white = '#a9b1d6'

# Selection
selection-background = '#283457'
selection-foreground = '#c0caf5'


# Light
light-black = '#414868'
light-green = '#9ece6a'
light-red = '#f7768e'
light-blue = '#7aa2f7'
light-yellow = '#e0af68'
light-magenta = '#bb9af7'
light-white = '#a9b1d6'
