# ----------------------------------------------------- 
# General window layout and colors
# name: "Default"
# ----------------------------------------------------- 

general { 
  gaps_in = 5
  gaps_out = 5

  border_size = 2

  # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
  # col.active_border = rgb(f5c2e7) rgb(cba6f7) 45deg
  col.active_border = rgb(89b4fa) rgb(cba6f7) 45deg
  # col.active_border = rgba(33ccffee)
  # col.inactive_border = rgba(595959aa)
  col.inactive_border = rgb(585b70)

  resize_on_border = false 
  allow_tearing = false
  layout = dwindle
}
