#################################
#  Load Tokyonight-Night theme #
#################################

include = ~/.config/foot/themes/catppuccin-mocha.ini

##########
#  Font #
##########

# font = MesloLGS Nerd Font Propo:size=10.6
font = JetBrainsMono Nerd Font Mono:size=11.6

###########
#  Title #
###########

title = Foot
