# ------------------------------------------------------ #
#  Preferred applications                               #
# ------------------------------------------------------ #

# Run prompt
$menu = runapp -- wofi --show drun
$menuRun = runapp -- wofi --show run

# Terminal
$terminal = runapp -- footclient
$terminal_restart = killall foot; foot --server
$terminal_alt = runapp -- kitty
$des_file_search = footclient --app-id float-term env BAT_THEME=tokyonight_night $HOME/.local/bin/des -f
$des_name_search = footclient --app-id float-term env BAT_THEME=tokyonight_night $HOME/.local/bin/des -n

# Polkit
$polkit = runapp -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Other
$fileManager = runapp -- pcmanfm
$calc = runapp -- gnome-calculator
$emojiPicker = runapp -- flatpak run it.mijorus.smile
$browser = runapp -- /opt/zen-browser-bin/zen-bin
$bluetooth = runapp -- footclient bluetui
$gtk_theme_setter = runapp -- nwg-look
