# ------------------------------------------------------ #
#  Preferred applications                               #
# ------------------------------------------------------ #

# Run prompt
$menu = runapp -- wofi --show drun
$menuRun = runapp -- wofi --show run

# Terminal
$terminal = runapp -- kitty --single-instance
$terminal_restart = killall foot; foot --server
$terminal_alt = runapp -- foot
$terminal_float = runapp -- kitty --app-id float-term
# $terminal_alt_float = runapp -- foot --app-id float-term
$des_file_search = $terminal_float env BAT_THEME="Catppuccin Mocha" $HOME/.local/bin/des -f
$des_name_search = $terminal_float env BAT_THEME="Catppuccin Mocha" $HOME/.local/bin/des -n
$wclass_search = $terminal_float env BAT_THEME="Catppuccin Mocha" $HOME/.local/bin/wclass_search
$taskManager = $terminal btop

# Polkit
$polkit = runapp -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Other
$fileManager = runapp -- $terminal yazi
$fileManagerAlt = runapp -- nautilus -w
$calc = runapp -- gnome-calculator
$emojiPicker = runapp -- flatpak run it.mijorus.smile
$browser = runapp -- /opt/zen-browser-bin/zen-bin
$bluetooth = runapp -- $terminal bluetui
$gtk_theme_setter = runapp -- nwg-look

# Volume
$volNotification = $HOME/.local/bin/volume_notification
$volUp = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && $volNotification
$volDown = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && $volNotification
$volMute = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
