layerrule = blur on, match:namespace launcher
layerrule = no_anim on, match:namespace hyprpicker
layerrule = animation fadeIn, match:namespace hyprshutdown
layerrule = no_anim on, match:namespace awww-daemon
