# ----------------------------------------------------- #
#  Window rules                                        #
# ----------------------------------------------------- #

# GNOME Calculator
windowrule = match:class org.gnome.Calculator, float on
windowrule = match:class org.gnome.Calculator, size 410 540

# Opacity
windowrule = match:class piper, opacity 0.9
windowrule = match:class org.gnome.Nautilus, opacity 0.9
windowrule = match:class io.missioncenter.MissionCenter, opacity 0.9

# Smile emoji picker
windowrule = match:class it.mijorus.smile, float on

# Setup for menus
# windowrule=noblur,class:^()$,title:^()$
# windowrule=rounding 3,class:^()$,title:^()$


windowrule = match:class Xdg-desktop-portal-gtk, no_blur on
windowrule = match:class Xdg-desktop-portal-gtk, border_size 0
windowrule = match:class Xdg-desktop-portal-gtk, no_shadow on

windowrule = match:class float-term, float on
windowrule = match:class float-term, size 1700 934
windowrule = match:class float-term, border_color rgb(cba6f7)
windowrule = match:class float-term, border_color rgb(cba6f7) rgb(f5c2e7) 45deg
windowrule = match:class float-term, border_size 2
