# ----------------------------------------------------- #
#  Window rules                                        #
# ----------------------------------------------------- #

# GNOME Calculator
windowrule = match:class org.gnome.Calculator, float on
windowrule = match:class org.gnome.Calculator, size 410 540

# Opacity (Ordered in how much I use them)
# windowrule = opacity 0.8,class:^(zen)$
# windowrule = opacity 0.85,class:^(net.nokyan.Resources)$
# windowrule = opacity 0.8,class:^(Pcmanfm)$
# windowrule = opacity 0.8,class:^(org.gnome.Nautilus)$
# windowrule = opacity 0.8,class:^(nwg-look)$
# windowrule = opacity 0.8,class:^(com.github.tchx84.Flatseal)$
# windowrule = opacity 0.8,class:^(org.prismlauncher.PrismLauncher)$
# windowrule = opacity 0.8,class:^(com.usebottles.bottles)$
# windowrule = opacity 0.8,class:^(localsend)$
# windowrule = opacity 0.8,title:^(Calculator)$
# windowrule = opacity 0.8,class:^(qt5ct)$
# windowrule = opacity 0.8,class:^(qt6ct)$
# windowrule = opacity 0.8,class:^(piper)$
# windowrule = opacity 0.8,class:^(it.mijorus.smile)$
# windowrule = opacity 0.8,class:^(vesktop)$
# windowrule = opacity 0.8,class:^(polkit-gnome-authentication-agent-1)$
# windowrule = opacity 0.8,class:^(com.obsproject.Studio)$
# windowrule = opacity 0.8,class:^(blueman-manager)$

# Smile emoji picker
windowrule = match:class it.mijorus.smile, float on

# Setup for menus
# windowrule=noblur,class:^()$,title:^()$
# windowrule=rounding 3,class:^()$,title:^()$


windowrule = match:class Xdg-desktop-portal-gtk, no_blur on
windowrule = match:class Xdg-desktop-portal-gtk, border_size 0
windowrule = match:class Xdg-desktop-portal-gtk, no_shadow on
