###################
### 󰊕 FUNCTIONS ###
###################

# Section: Privilage esclation tool

## Code generated by ChatGPT 4o and GPT 4o mini (modified by Chen) ##
priv_escal_tool="sudo"
function __priv-escal-tool-command() {
    local orig_cursor=$CURSOR  # Save the original cursor position

    if [[ -z "${BUFFER}" ]]; then
        # If the buffer is empty, just insert "$priv_escal_tool " and move to the end
        BUFFER="$priv_escal_tool "
        zle end-of-line
    elif [[ "${BUFFER}" == $priv_escal_tool\ * ]]; then
        # If the buffer starts with "$priv_escal_tool ", remove it
        BUFFER="${BUFFER#$priv_escal_tool }"
        CURSOR=$((orig_cursor - 5))  # Adjust cursor position
    else
        # Prepend "$priv_escal_tool " and move the cursor to the end of the buffer
        BUFFER="$priv_escal_tool ${BUFFER}"
        CURSOR=$((orig_cursor + 5))  # Adjust cursor position
    fi
    zle reset-prompt  # Refresh prompt to update syntax highlighting
}
zle -N __priv-escal-tool-command
bindkey '\e\e' __priv-escal-tool-command
